### ISSUE TITLE
AsmJs/WAsm calling convention issues on xplat

### ISSUE THREAD

**Issue by Penguinwizzard** [Microsoft/ChakraCore#2378]
When attempting to pass a floating-point argument to an asmjs/wasm function on xplat, the caller and callee don't agree on the calling convention. This causes correctness issues, as we end up often using the wrong value. This occurs in JITted code.

**Repro:**
Remove these lines from test/runtest.py ([link](https://github.com/Microsoft/ChakraCore/blob/master/test/runtests.py#L129-L130)):
```python
not_compile_flags = set(['-simdjs']) \  
    if sys.platform != 'win32' else None
```
Run `runtests.py -d AsmJSFloat`.

Note: There's a separate bug filed related to removing the lines hiding this issue from runtest.py at https://github.com/Microsoft/ChakraCore/issues/2412.

**Repro file:**
Here's a separate file by @Cellule that reproduces the issue with -maic:0
```js
function AsmModuleDouble() {
        "use asm";

        function add(x) {
                    x = +x;
                    return +sub(1.5);
                }
        function sub(x) {
                    x = +x;
                    return +(x);
                }
        return {
                    add: add
                };
}

var asmModuleDouble = AsmModuleDouble();     // produces AOT-compiled version
print(asmModuleDouble.add(2, 1))
```

**Comment by jianchun** [comment]
@Penguinwizzard Indeed, didn't get to complete Simd when I worked on xplat JIT. That's why Simd tests were disabled on xplat by that line.

**Comment by Cellule** [comment]
From what I was able to gather this happens because `LowererMDArch::LowerCallArgs` calls in `LowererMDArch::GetArgSlotOpnd` which tries to use xmm registers for float argument when we are supposed to put them on the stack on xplat

**Comment by Cellule** [comment]
@jianchun The problem is almost all asm.js test have that flag even though simd is not used (I am not entirely sure the reason why, but I think there's a good one).

**Comment by Penguinwizzard** [comment]
@jianchun If Simd doesn't work on xplat, should we disable building Simd/not recognize the flag on xplat?

**Comment by jianchun** [comment]
@Penguinwizzard @Cellule At the time I felt Simd was close to completion, but I was not exactly sure of the calling conventions. Left Simd code in build so it would not diverge further (Simd code kept introducing build failures at the time).

**Comment by MikeHolman** [comment]
Is wrong calling convention still an issue?

**Comment by Cellule** [comment]
@MikeHolman AFAIK it hasn't been fixed yet, but maybe @obastemur has more info on this

**Comment by MikeHolman** [comment]
Then can we increase the priority on this issue? It is essentially blocking our wasm fuzzing and generally is a pretty high impact issue for wasm/asm.js code.

**Comment by obastemur** [comment]
#2716 is merged and should fix this issue.

**Comment by Penguinwizzard** [comment]
Problems still occur; remove exclude_xplat on most wasm test cases to repro.

**Comment by obastemur** [comment]
@Penguinwizzard the problem shouldn't be calling conventions. At least it was fixed for asm.js and others. About WASM, we have couple of disable stuff (SIMD) for xplat. Maybe we should close this issue and open a new one : `Enable WASM on xplat` ?

**Comment by Cellule** [comment]
This issue is also hitting in asm.js not just wasm.
One of the problem is how we make calls in jitted code which is shared by both asm.js and wasm

**Comment by Cellule** [comment]
Closing in favor of #3561
