### ISSUE TITLE
VS2017 internal error occurred when building ChakraCore

### ISSUE THREAD

**Issue by xiaoyinl** [Microsoft/ChakraCore#3612]
After I updated Visual Studio 2017 to version 15.3.3 today, it can't build ChakraCore (master branch, x86 release version). The error is: **fatal error C1001: An internal error has occurred in the compiler.** and **LINK : fatal error LNK1000: Internal error during IMAGE::BuildImage**. The x86 debug and x64 release versions can be built successfully. I am using Visual Studio 2017 Community Edition on Windows 10 x64 Build 15063. Does anyone else notice the same problem? Is there any workaround?

Here is the log:
```
15>   Creating library C:\Users\***\git\ChakraCore\Build\VcBuild\bin\x86_release\ChakraCore.lib and object C:\Users\***\git\ChakraCore\Build\VcBuild\bin\x86_release\ChakraCore.exp
15>Generating code
15>c:\users\***\git\chakracore\lib\backend\serverscriptcontext.cpp : fatal error C1001: An internal error has occurred in the compiler.
15>(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 256)
15> To work around this problem, try simplifying or changing the program near the locations listed above.
15>Please choose the Technical Support command on the Visual C++
15> Help menu, or open the Technical Support help file for more information
15>  link!InvokeCompilerPass()+0x1f81f
15>  link!InvokeCompilerPass()+0x1f81f
15>  link!InvokeCompilerPass()+0x26d8c
15>  link!InvokeCompilerPass()+0x2722d
15>  link!DllGetC2Telemetry()+0xf4a80
15>  link!CloseTypeServerPDB()+0x53a92
15>  link!CloseTypeServerPDB()+0x5adbf
15>  link!CloseTypeServerPDB()+0x5ab47
15>
15>c:\users\***\git\chakracore\lib\backend\serverscriptcontext.cpp : fatal error C1001: An internal error has occurred in the compiler.
15>(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 256)
15> To work around this problem, try simplifying or changing the program near the locations listed above.
15>Please choose the Technical Support command on the Visual C++
15> Help menu, or open the Technical Support help file for more information
15>  link!InvokeCompilerPass()+0x1f81f
15>  link!InvokeCompilerPass()+0x26d8c
15>  link!InvokeCompilerPass()+0x2722d
15>  link!DllGetC2Telemetry()+0xf4a80
15>  link!CloseTypeServerPDB()+0x53a92
15>  link!CloseTypeServerPDB()+0x5adbf
15>  link!CloseTypeServerPDB()+0x5ab47
15>
15>
15>LINK : fatal error LNK1000: Internal error during IMAGE::BuildImage
15>
15>  Version 14.11.25507.1
15>
15>  ExceptionCode            = C0000005
15>  ExceptionFlags           = 00000000
15>  ExceptionAddress         = 50DBE9AB (509D0000) "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x86\c2.dll"
15>  NumberParameters         = 00000002
15>  ExceptionInformation[ 0] = 00000000
15>  ExceptionInformation[ 1] = 00000001
15>
15>CONTEXT:
15>  Eax    = 00000000  Esp    = 0075E5EC
15>  Ebx    = 34E34DB8  Ebp    = 0075E5F8
15>  Ecx    = 34E35AFC  Esi    = 00000005
15>  Edx    = 00000002  Edi    = 1A8F4474
15>  Eip    = 50DBE9AB  EFlags = 00010246
15>  SegCs  = 00000023  SegDs  = 0000002B
15>  SegSs  = 0000002B  SegEs  = 0000002B
15>  SegFs  = 00000053  SegGs  = 0000002B
15>  Dr0    = 00000000  Dr3    = 00000000
15>  Dr1    = 00000000  Dr6    = 00000000
15>  Dr2    = 00000000  Dr7    = 00000000
15>Done building project "ChakraCore.vcxproj" -- FAILED.
========== Build: 14 succeeded, 1 failed, 10 up-to-date, 0 skipped ==========
```

**Comment by fatcerberus** [comment]
I'm getting this too.  Debug builds work fine, but Release build fails with internal errors during code generation.  Probably should be reported upstream to the MSVC devs.

**Comment by xiaoyinl** [comment]
@fatcerberus Thanks for the suggestion! I reported it to Visual Studio here: https://developercommunity.visualstudio.com/content/problem/108800/fatal-error-c1001-an-internal-error-has-occurred-i-7.html

**Comment by xiaoyinl** [comment]
@fatcerberus I fixed the building error by running "Rebuild Solution". I'm not sure if we had the same issue, but I suggest you try it if you haven't.

**Comment by fatcerberus** [comment]
Still getting this in MSVC 2017 v15.3.5 when building x64 Release.

```js
3>------ Build started: Project: ChakraCore, Configuration: Release x64 ------
3>   Creating library C:\src\ChakraCore\Build\VcBuild\bin\x64_release\ChakraCore.lib and object C:\src\ChakraCore\Build\VcBuild\bin\x64_release\ChakraCore.exp
3>Generating code
3>  link!InvokeCompilerPass()+0x1f40b
3>  link!InvokeCompilerPass()+0x1f40b
3>  link!InvokeCompilerPass()+0x269a2
3>  link!InvokeCompilerPass()+0x26e34
3>  link!DllGetC2Telemetry()+0x11dcca
3>
3>c:\src\chakracore\lib\jsrt\core\jsrtcontextcore.cpp : fatal error C1001: An internal error has occurred in the compiler.
3>(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 256)
3> To work around this problem, try simplifying or changing the program near the locations listed above.
3>Please choose the Technical Support command on the Visual C++
3> Help menu, or open the Technical Support help file for more information
3>c:\src\chakracore\lib\jsrt\core\jsrtcontextcore.cpp : fatal error C1001: An internal error has occurred in the compiler.
3>(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 256)
3> To work around this problem, try simplifying or changing the program near the locations listed above.
3>Please choose the Technical Support command on the Visual C++
3> Help menu, or open the Technical Support help file for more information
3>  link!InvokeCompilerPass()+0x1f40b
3>  link!InvokeCompilerPass()+0x269a2
3>  link!InvokeCompilerPass()+0x26e34
3>  link!DllGetC2Telemetry()+0x11dcca
3>
3>
3>LINK : fatal error LNK1000: Internal error during IMAGE::BuildImage
3>
3>  Version 14.11.25508.2
3>
3>  ExceptionCode            = C0000005
3>  ExceptionFlags           = 00000000
3>  ExceptionAddress         = 03FE1BB8 (03C00000) "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\c2.dll"
3>  NumberParameters         = 00000002
3>  ExceptionInformation[ 0] = 00000000
3>  ExceptionInformation[ 1] = 00000001
3>
3>CONTEXT:
3>  Eax    = 00000000  Esp    = 008FE8BC
3>  Ebx    = 44B48745  Ebp    = 008FE8C8
3>  Ecx    = 44B493B4  Esi    = 00000005
3>  Edx    = 00000002  Edi    = 1B3B3F74
3>  Eip    = 03FE1BB8  EFlags = 00010246
3>  SegCs  = 00000023  SegDs  = 0000002B
3>  SegSs  = 0000002B  SegEs  = 0000002B
3>  SegFs  = 00000053  SegGs  = 0000002B
3>  Dr0    = 00000000  Dr3    = 00000000
3>  Dr1    = 00000000  Dr6    = 00000000
3>  Dr2    = 00000000  Dr7    = 00000000
3>Done building project "ChakraCore.vcxproj" -- FAILED.
```

**Comment by MikeHolman** [comment]
I've seen these before, and I think they are generally to do with incremental linking being buggy. Whenever I see this, doing a rebuild or clean+build fixes the issue. Did that not work for you?

**Comment by fatcerberus** [comment]
Yes, full rebuild fixed the issue.  I guess I never run into this because I habitually disable incremental linking in my own projects.
