### ISSUE TITLE
Top-level module with no imports produces SyntaxError

### ISSUE THREAD

**Issue by fatcerberus** [Microsoft/ChakraCore#3617]
The following module parses successfully:
```js
import { from } from 'cell-runtime';

Object.assign(Sphere.Game,
{
	name:       "kh2Bar Showcase",
	author:     "Fat Cerberus",
	resolution: '320x240',
	main:       '@/bin/main.mjs',
});

install('@/bin', files('src/*.mjs', true));

install('@/images', files('images/*.png', true));
install('@/sounds', files('sounds/*.wav', true));
```

However, if I remove or comment out the line:
```js
import { from } from 'cell-runtime';
```

Loading this as a root module now produces a SyntaxError with no message (note: error reporting for module parsing clearly needs work).

There seems to be no such requirement for child modules -- they can have no imports at all and parse just fine.  But the root module seems to be required to have at least one import.  Is this a bug?

**Comment by fatcerberus** [comment]
I worked around this by evaluating a fake root module that imports the real one.  That said, I couldn't find anything in the ECMAScript specification that says the root module must have at least one import, so I'm thinking this is a bug.

**Comment by suwc** [comment]
@fatcerberus thanks for filing the issue.
I tried to reproduce the SyntaxError but hadn't had the luck. Would you be so kind to share a mini test case with ch.exe?

**Comment by fatcerberus** [comment]
I can't even get ch.exe to run any modules at all, everything I try results in a syntax error.

**pig.js**
```js
WScript.LoadModule('./pigmod.js');
```

**pigmod.js**
```js
import { Cow } from './cowmod.js';

Cow.eat("kitties");
```

**cowmod.js**
```js
export
class Cow
{
    static eat(what)
    {
        console.log(`the cow ate a bunch of ${what}`);
    };
}
```

**Output**
```
D:\src\ChakraCore\Build\VcBuild\bin\x64_debug>ch --ES6Module pig.js
thrown at moduleScript1.js:
^
SyntaxError: Syntax error
SyntaxError: Syntax error
   at Global code (D:\src\ChakraCore\Build\VcBuild\bin\x64_debug\pig.js:1:1)
```

**Comment by fatcerberus** [comment]
By the way: ChakraCore version is v1.7.1.

**Comment by suwc** [comment]
@fatcerberus, thanks!
Could you try this?

```javascript
// pig.js
WScript.LoadScriptFile("./pigmod.js", "module");
```

**Comment by fatcerberus** [comment]
Changing LoadModule to LoadScriptFile indeed got the module to run - however I also can't reproduce the original syntax error with ch.exe.  I'll do some more digging.

**Comment by akroshg** [comment]
As I understand this issue is resolved bug using the LoadScriptFile.

**Comment by fatcerberus** [comment]
@akroshg No, the original bug I encountered was different: Passing a module with no `import` directives to a top-level `JsParseModuleSource()` call (= referencing module record is nullptr) results in a syntax error.

**Comment by fatcerberus** [comment]
@akroshg Can this issue be reopened?  The problem is still present in CC 1.7.2.

Repro:
```c
	JsModuleRecord rec;
	JsValueRef url;
	JsCreateString("foo.mjs", 7, &url);
	JsInitializeModuleRecord(NULL, url, &rec);
	JsSetModuleHostInfo(rec, JsModuleHostInfo_FetchImportedModuleCallback, on_import_module);
	JsSetModuleHostInfo(rec, JsModuleHostInfo_HostDefined, url);
	JsSourceContext cookie = 812;
	const char* src = "let x = Math.max(812, 1208);";
	JsValueRef exc;
	JsErrorCode err = JsParseModuleSource(rec,
		cookie, (BYTE*)src, (unsigned int)strlen(src),
		JsParseModuleSourceFlags_DataIsUTF8, &exc);
```

At this point `err` is JsErrorScriptCompile and `exc` refers to a SyntaxError with no message.

**Comment by obastemur** [comment]
@akroshg not sure who to assign, so assigned it to you :)

**Comment by akroshg** [comment]
It seems like JsModuleHostInfo_NotifyModuleReadyCallback is missing.
I modified your code as below and this should work

```cpp
    static JsErrorCode CALLBACK FIMC1(_In_ JsModuleRecord referencingModule, _In_ JsValueRef specifier, _Outptr_result_maybenull_ JsModuleRecord* dependentModuleRecord)
    {
        return JsNoError;
    }

    static JsErrorCode CALLBACK NMRC1(_In_opt_ JsModuleRecord referencingModule, _In_opt_ JsValueRef exceptionVar)
    {
        return JsNoError;
    }

    void SomebugTest(JsRuntimeAttributes attributes, JsRuntimeHandle runtime)
    {
        JsModuleRecord rec;
        JsValueRef url;
        JsCreateString("foo.js", 7, &url);
        JsInitializeModuleRecord(NULL, url, &rec);
        JsSetModuleHostInfo(rec, JsModuleHostInfo_FetchImportedModuleCallback, FIMC1);
        JsSetModuleHostInfo(rec, JsModuleHostInfo_HostDefined, url);
        JsSetModuleHostInfo(rec, JsModuleHostInfo_NotifyModuleReadyCallback, NMRC1);
        JsSourceContext cookie = 812;
        const char* src = "let x = Math.max(812, 1208);";
        JsValueRef exc;
        JsErrorCode err = JsParseModuleSource(rec,
            cookie, (BYTE*)src, (unsigned int)strlen(src),
            JsParseModuleSourceFlags_DataIsUTF8, &exc);
        CHECK(err == JsNoError);

    }
```

**Comment by fatcerberus** [comment]
That's interesting.  I didn't set a NotifyModuleReadyCallback in my engine because I load modules synchronously, but it's weird, if you add an import to the test code then it succeeds with no error, even without the callback being set.

**Comment by fatcerberus** [comment]
Setting a module ready callback fixed the issue.  Not a ChakraCore bug (except for the unhelpful syntax error), so closing.
