### ISSUE TITLE
Null pointer dereference in Runtime/ByteCode/ByteCodeEmitter.cpp:8810

### ISSUE THREAD

**Issue by zhiyi01** [Microsoft/ChakraCore#6059]
the following js fragment causes a null pointer dereference.

```javascript
function foo() {
    for (var h = 0;; ++h) {
        for (var r = 0; ; ++r) {
            var a =1;
        }
    }
};
foo();
```

Version: Release v1.11.7
OS: Ubuntu 16.04.1 LTS
Arch: x86_64

**Comment by MikeHolman** [comment]
Looks like this is already fixed in master.

**Comment by zhiyi01** [comment]
This bug was not fixed. It can be triggered in the Release v1.11.8 @MikeHolman
